### ISSUE TITLE
UDataTable loading issue

### ISSUE THREAD

**Issue by GMatrixGames** [Sprayxe/unreal.js#3]
**Describe the bug**
When loading pretty much any UDataTable, you get a stacktrace similar to the one shown in the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/25112532/123557094-fa39ff00-d75c-11eb-8f9a-1c80c468a262.png)
![image](https://user-images.githubusercontent.com/25112532/123557141-3ec59a80-d75d-11eb-9be5-719b86f5c0b0.png)

**Additional information**
1. Unreal.JS Version - 1.0.6
2. Game (+ Version) - Fortnite + 17.10
3. Path to file (if applicable) - `FortniteGame/Content/Athena/Balance/DataTables/CashPricing`

**Comment by Sprayxe** [comment]
Fixed in the next update
