### ISSUE TITLE
Game plugins seem to not load

### ISSUE THREAD

**Issue by GMatrixGames** [Sprayxe/unreal.js#4]
**Describe the bug**
Loading a package from a plugin always (from what files I've tested) returns null.

**Screenshots**
![image](https://user-images.githubusercontent.com/25112532/123557188-7cc2be80-d75d-11eb-812b-545968601be1.png)

**Additional information**
1. Unreal.JS Version - 1.0.6
2. Game (+ Version) - Fortnite + 17.10
3. Path to file (if applicable) - `FortniteGame/Plugins/GameFeatures/NPCLibrary/Content/NPCs/Turk/Turk/NPCLibrary_Conversation_Turk`

The screenshot shows that CUE4Parse can parse it correctly

**Comment by Sprayxe** [comment]
Paths to game plugins are being changed by the library. Your path should be: `/NPCLibrary/NPCs/Turk/Turk/NPCLibrary_Conversation_Turk`
Try loading it using this path

**Comment by Sprayxe** [comment]
Fixed the update, will be included in the next update
