### ISSUE TITLE
ParseExceptions while exporting JSON of Fortnite character cosmetic files

### ISSUE THREAD

**Issue by Corgan** [Sprayxe/unreal.js#9]
**Describe the bug**
Getting multiple "FName could not be read", "Invalid String length" and "Serialized FString is not null-terminated" ParseExceptions.

**Screenshots**
N/A

**Additional information**
Code and Logfile, https://gist.github.com/Corgan/175e7b5c4c3568fa50471077959811ec

unreal.js@1.0.9
Fortnite 17.10
++Fortnite+Release-17.10-CL-16745144-Windows

**Comment by Sprayxe** [comment]
Fixed
